version: '3.7'

services:
  db:
    container_name: muerta-db
    image: ak1m1tsu/muerta-db:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
  api:
    container_name: muerta-api
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - API_NAME=${API_NAME}
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    ports:
      - '0372:${PORT}'
    links:
      - db
    volumes:
      - ./:/api
volumes:
  data:
    driver: local
