version: '3.7'

services:
  db:
    container_name: muerta-db
    build:
      context: ./
      dockerfile: .docker/db/Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
  api:
    container_name: muerta-api
    build:
      context: ./
      dockerfile: .docker/api/Dockerfile
    depends_on:
      - db
    ports:
      - '8000:8000'
    links:
      - db
    volumes:
      - ./:/api
volumes:
  data:
    driver: local
