version: '3.7'

services:
  db:
    container_name: muerta-db
    image: ak1m1tsu/muerta-db:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
  cache:
    container_name: muerta-cache
    image: redis:alpine
    restart: always
    ports:
      - '6379:${CACHE_PORT}'
    volumes:
      - cache:/data
  web:
    container_name: muerta-proxy
    build: .docker/nginx
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${PORT}
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    container_name: muerta-api
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - API_NAME=${API_NAME}
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - CACHE_HOST=${CACHE_HOST}
      - CACHE_USER=${CACHE_USER}
      - CACHE_PASSWORD=${CACHE_PASSWORD}
      - CACHE_PORT=${CACHE_PORT}
    depends_on:
      - db
      - cache
    ports:
      - '${PORT}:${PORT}'
    links:
      - db
    volumes:
      - ./:/api
volumes:
  cache:
  data:
    driver: local
