postgres:
  user: postgres
  password: postgres
  database: exhort
  host: localhost
  port: 5432
server:
  addr: localhost:3000
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 120s
redis:
  user: default
  password: guest
  host: localhost
  database: 0
  port: 6379
  read_timeout: 10s
  write_timeout: 10s
  dial_timeout: 10s
  shutdown_time: 5s
access:
  expiration: 5m
refresh:
  expiration: 15m
rabbitmq:
  host: localhost
  port: 5672
  user: guest
  password: guest
  queue_name: welcome_message
