basePath: /api/v1
definitions:
  dto.Response:
    properties:
      data:
        additionalProperties: {}
        type: object
      success:
        example: true
        type: boolean
    type: object
info:
  contact: {}
  description: Web API to control the shelf life of products using computer vision
  termsOfService: http://swagger.io/terms
  title: Muerta API
  version: 1.0.0
paths:
  /auth/sign-up:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Sign Up user
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authrization
    type: apiKey
swagger: "2.0"
